name: Wordlist Updater - Awesome list of secrets in environment variables

on:
  schedule:
    - cron: '0 0 1 * *'  # once a month at midnight (thanks https://crontab.guru)

jobs:
  update_awesome-environment-variable-names:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate awesome-environment-variable-names.txt
        run: cd Discovery/Variables && wget https://raw.githubusercontent.com/Puliczek/awesome-list-of-secrets-in-environment-variables/main/raw_list.txt -O awesome-environment-variable-names.txt

      - name: Switching from HTTPS to SSH
        run: git remote set-url origin git@github.com:danielmiessler/SecLists.git

      - name: Stage changed files
        run: git add Discovery/Variables/awesome-environment-variable-names.txt

      - name: Configure git email and username
        run: |
          git config --local user.email "example@github.com"
          git config --local user.name "GitHub Action"

      - name: Check git status and save to output
        id: myoutputs
        run: |
          git status
          echo "::set-output name=gitstatus::$(git status --porcelain)"

      - name: Commit changed files
        if: steps.myoutputs.outputs.gitstatus != ''
        run: git commit -m "[Github Action] Updated awesome-environment-variable-names.txt"

      - name: Push changes # push the output folder to your repo
        if: steps.myoutputs.outputs.gitstatus != ''
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
